#[allow(dead_code)]
#[derive(Copy, Clone)]
pub enum Icon {
    AlignJusitify,
    Bars,
    Blockquote,
    Bold,
    Check,
    Checkbox,
    ChevronLeft,
    ChevronRight,
    Code,
    Computer,
    Copy,
    Cross,
    CrossOut,
    Delete,
    Download,
    GitHub,
    Help,
    Heading,
    Image,
    Info,
    Italic,
    Line,
    Link,
    Loading,
    Markdown,
    Monospace,
    Moon,
    OrderedList,
    Read,
    Split,
    Subscript,
    Sun,
    Superscript,
    Table,
    Underline,
    UnorderedList,
    Write,
}

impl Icon {
    pub fn as_fontawesome(self) -> String {
        match self {
            Self::Table => String::from("fa-solid fa-table"),
            Self::Bold => String::from("fa-solid fa-bold"),
            Self::Checkbox => String::from("fa-solid fa-square-check"),
            Self::Link => String::from("fa-solid fa-link"),
            Self::Loading => String::from("fa-solid fa-circle-notch fa-spin"),
            Self::UnorderedList => String::from("fa-solid fa-list-ul"),
            Self::Image => String::from("fa-solid fa-image"),
            Self::OrderedList => String::from("fa-solid fa-list-ol"),
            Self::Blockquote => String::from("fa-solid fa-quote-right"),
            Self::Italic => String::from("fa-solid fa-italic"),
            Self::CrossOut => String::from("fa-solid fa-strikethrough"),
            Self::Download => String::from("fa-solid fa-download"),
            Self::Heading => String::from("fa-solid fa-heading"),
            Self::Computer => String::from("fa-solid fa-computer"),
            Self::Copy => String::from("fa-solid fa-copy"),
            Self::Code => String::from("fa-solid fa-code"),
            Self::Split => String::from("fa-solid fa-table-columns"),
            Self::Read => String::from("fa-solid fa-eye"),
            Self::Write => String::from("fa-solid fa-pencil"),
            Self::Delete => String::from("fa-solid fa-trash-can"),
            Self::Markdown => String::from("fa-brands fa-markdown"),
            Self::Line => String::from("fa-solid fa-minus"),
            Self::Cross => String::from("fa-solid fa-xmark"),
            Self::Check => String::from("fa-solid fa-check"),
            Self::Monospace => String::from("fa-solid fa-text-width"),
            Self::AlignJusitify => String::from("fa-solid fa-align-justify"),
            Self::Underline => String::from("fa-solid fa-underline"),
            Self::Subscript => String::from("fa-solid fa-subscript"),
            Self::Superscript => String::from("fa-solid fa-superscript"),
            Self::Help => String::from("fa-solid fa-circle-question"),
            Self::Info => String::from("fa-solid fa-circle-info"),
            Self::GitHub => String::from("fa-brands fa-github"),
            Self::Moon => String::from("fa-solid fa-moon"),
            Self::Sun => String::from("fa-solid fa-sun"),
            Self::Bars => String::from("fa-solid fa-bars"),
            Self::ChevronLeft => String::from("fa-solid fa-chevron-left"),
            Self::ChevronRight => String::from("fa-solid fa-chevron-right"),
        }
    }
}
